"""Added RestaurantMedia and FoodType changes

Revision ID: 5600525440a0
Revises: 8e7baf63dd72
Create Date: 2026-03-22 10:53:48.900617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5600525440a0'
down_revision = '8e7baf63dd72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_table('restaurant_media',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('restaurant_id', sa.Integer(), nullable=False),
        sa.Column('media_type', sa.String(length=20), nullable=False),
        sa.Column('url', sa.String(length=255), nullable=False),
        sa.Column('display_order', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    except Exception as e:
        print("Table might exist", e)

    try:
        with op.batch_alter_table('food_types', schema=None) as batch_op:
            batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
    except Exception as e:
        pass
    try:
        with op.batch_alter_table('food_types', schema=None) as batch_op:
            batch_op.add_column(sa.Column('requested_by_id', sa.Integer(), nullable=True))
    except Exception as e:
        pass
    try:
        with op.batch_alter_table('food_types', schema=None) as batch_op:
            batch_op.create_foreign_key('fk_food_types_requested_by_id', 'users', ['requested_by_id'], ['id'])
    except Exception as e:
        pass

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('profile_image',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('profile_image',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('food_types', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('requested_by_id')
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
